"""initial_migration

Revision ID: fff1d2b34c03
Revises: 
Create Date: 2026-07-04 16:53:50.850126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff1d2b34c03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('goal', sa.Enum('RECOMPOSITION', 'CUT', 'BULK', name='usergoal'), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата та час створення запису'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата та час останнього оновлення запису'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата прийому їжі / логування'),
    sa.Column('total_calories', sa.Integer(), nullable=False, comment='Калорійність (ккал)'),
    sa.Column('protein', sa.Float(), nullable=True, comment='Білки (г)'),
    sa.Column('carbs', sa.Float(), nullable=True, comment='Вуглеводи (г)'),
    sa.Column('fats', sa.Float(), nullable=True, comment='Жири (г)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата та час створення запису'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата та час останнього оновлення запису'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_date'), 'nutrition_logs', ['date'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата тренування'),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False, comment='Вага обтяження в кг'),
    sa.Column('sets', sa.Integer(), nullable=False, comment='Кількість підходів'),
    sa.Column('reps', sa.Integer(), nullable=False, comment='Кількість повторень'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата та час створення запису'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата та час останнього оновлення запису'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_logs_date'), 'workout_logs', ['date'], unique=False)
    op.create_index(op.f('ix_workout_logs_exercise_name'), 'workout_logs', ['exercise_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_exercise_name'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_date'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_nutrition_logs_date'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
